apiVersion: v1
kind: ConfigMap
metadata:
  name: ecom-backend-config
  namespace: ecom1
data:
  PORT: "5000"
  JWT_EXPIRE: "30d"
  COOKIE_EXPIRE: "30"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "465"
  SMTP_SERVICE: "gmail"
  SMTP_MAIL: "modinisree@gmail.com"
