apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-frontend
  namespace: ecom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-frontend
  template:
    metadata:
      labels:
        app: ecom-frontend
    spec:
      containers:
      - name: frontend
        image: modinipadmasree/ecom-frontend:3
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: ecom-frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-frontend-svc
  namespace: ecom
spec:
  type: LoadBalancer
  selector:
    app: ecom-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
